import React from 'react'

const Tos = () => {
  return (
<div class="padded-container px-10 space-y-10 pb-6 pt-8">
   <div class="align-start flex flex-col justify-between gap-5">
      <time datetime="2024-02-21T15:11:13.112Z" class="text-subtitle3 font-medium text-[#FF6243]">
         Last Updated: February 21, 2024
      </time>
      <h1 class="text-displayL5 text-whop-black text-4xl font-semibold md:text-5xl  font-display">Terms of Service</h1>
      <div class="space-y-4">
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Terms of Service</b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">Thank you for your interest in Whop, Inc. (“<b>Whop</b>,” “<b>we</b>,” or “<b>us</b>”) and our website at&nbsp;<a href="https://whop.com/" class="text-whop-primary underline"><u>www.whop.com</u></a>, along with our related websites, hosted applications, mobile or other downloadable applications, and other services provided by us (collectively, the “<b>Service</b>”). These Terms of Service are a legally binding contract between you and Whop regarding your use of the Service.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>PLEASE READ THE FOLLOWING TERMS CAREFULLY</b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>BY CLICKING</b>&nbsp;“<b>I ACCEPT</b>,”&nbsp;<b>OR BY DOWNLOADING, INSTALLING, OR OTHERWISE ACCESSING OR USING&nbsp;THE SERVICE</b>, YOU AGREE THAT YOU HAVE READ AND UNDERSTOOD, AND, AS A CONDITION TO YOUR&nbsp;USE OF THE SERVICE, YOU AGREE TO BE BOUND BY, THE FOLLOWING TERMS AND CONDITIONS,&nbsp;INCLUDING&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>WHOP’S PRIVACY POLICY</u></a>&nbsp;AND OTHER POLICIES REFERENCED BELOW (TOGETHER, THESE&nbsp;“<b>TERMS</b>”). IF YOU ARE NOT ELIGIBLE, OR DO NOT AGREE TO THE TERMS, THEN YOU DO NOT HAVE OUR PERMISSION TO USE THE SERVICE. YOUR USE OF THE SERVICE, AND WHOP’S PROVISION OF THE SERVICE TO YOU, CONSTITUTES AN AGREEMENT BY WHOP AND BY YOU TO BE BOUND BY THESE TERMS.&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>ARBITRATION NOTICE</b>. Except for certain kinds of disputes described in Section 18, you agree that disputes arising under these Terms will be resolved by binding, individual arbitration, and BY ACCEPTING THESE TERMS, YOU AND WHOP ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN ANY CLASS ACTION OR REPRESENTATIVE PROCEEDING.&nbsp;&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>1. Whop Service Overview</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">Whop operates the Service as a marketplace for digital goods and services (the “<b>Products</b>”) where certain users (“<b>Buyers</b>”) can purchase the Products sold by other users (“<b>Sellers</b>”). All Products are provided solely by the applicable Seller and Whop is not responsible for the Products sold through the Service.&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>2. Eligibility</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">You must be at least 13 years old to use the Service. By agreeing to these Terms, you represent and warrant to us that: (a) you are at least 13 years old; (b) you have not previously been suspended or removed from the Service; and (c) your registration and your use of the Service is in compliance with any and all applicable laws and regulations. If you are an entity, organization, or company, the individual accepting these Terms on your behalf represents and warrants that they have authority to bind you to these Terms and you agree to be bound by these Terms.&nbsp;<b>&nbsp;</b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>3. Accounts and Registration</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">To access most features of the Service, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself, such as your name, email address, or other contact information, and/or to link certain outside accounts, email addresses, phone numbers, other platforms, or a digital wallet (collectively, “<b>Linked Accounts</b>”). You agree that the information you provide to us is accurate, complete, and not misleading, and that you will keep it accurate and up to date at all times. You further agree that all Linked Accounts are your own and you have all necessary rights to link them to the Service, and you hereby authorize us to maintain the Linked Account as part of your account with us. When you register, you will be asked to create a password. You are solely responsible for maintaining the confidentiality of your account and password, and you accept responsibility for all activities that occur under your account. If you believe that your account is no longer secure, then you should immediately notify us at support@whop.com.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>4. General Payment Terms</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">Certain features of the Service, including the purchase or sale of certain Products, may require you to pay fees. Before you pay any fees, you will have an opportunity to review and accept the fees that you will be charged. All fees are denominated in the stated currency or other means of payment and are non-refundable unless otherwise specifically provided for in these Terms.&nbsp;</p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Price</b>. Whop reserves the right to determine pricing for the Service and any fees it may charge on transactions conducted on the Service. Whop will make reasonable efforts to keep pricing information published on the Service up to date. We encourage you to check our pricing page periodically for current pricing information. Whop may change the fees for any feature of the Service, including additional fees or charges, if Whop gives you advance notice of changes before they apply. Whop, at its sole discretion, may make promotional offers with different features and different pricing to any of Whop’s customers. These promotional offers, unless made to you, will not apply to your offer or these Terms.&nbsp;&nbsp;</li>
            <li><b>Authorization</b>. You authorize Whop to charge all sums for the orders that you make and any level of Service you select as described in these Terms or published by Whop, including all applicable taxes, to the payment method specified by you. If you pay any fees with a credit card, then Whop may seek pre-authorization of your credit card account prior to your purchase to verify that the credit card is valid and has the necessary funds or credit available to cover your purchase. If you are permitted to save a payment method (such as a credit card) or any Linked Account with a payment feature as part of your account with us, you authorize us to save and maintain such payment method or Linked Account and use it for the payment of various fees and amounts related to your purchase of Products or use of the Services.&nbsp;&nbsp;</li>
            <li>
               <b>Sales Tax and Withholding Taxes.</b>
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li><b>Sales, Use and Similar Taxes.&nbsp;</b>In some instances, Whop may have an obligation to add sales or use tax to the purchase price of Products. In such cases, Whop will list the appropriate taxes, and charge and collect them as part of the transaction and either remit the taxes to the applicable taxing authority or transmit the collected taxes to Sellers for Seller remittance and reporting to tax authorities.</li>
                  <li><b>Withholding Taxes.</b>&nbsp;In some instances, Whop may have agreed, in its sole discretion, to serve as the merchant of record for a given transaction related to the Services. As the merchant of record, Whop may be obligated to withhold tax amounts from payments to Sellers. Whop may withhold from any amounts payable to Sellers such federal, state, local or foreign taxes as shall be required to be withheld pursuant to any applicable law or regulation, as determined in Whop’s sole discretion. In instances where Whop is not the merchant of record, Whop does not bear any legal obligation or responsibility to, and will not, collect, report, and remit any such taxes on behalf of a Seller under any circumstances.&nbsp;</li>
               </ol>
            </li>
            <li><b>Product Price</b>. If you are a Seller, you may set or change the price for your Products at your sole discretion. You agree to keep all pricing information for your Products up to date and to abide by any of your listed prices for sold Products.&nbsp;&nbsp;</li>
            <li><b>Amount Paid to Sellers.</b>&nbsp;When one of your Products is sold, you will receive the net purchase price in the form of your base currency, minus (i) any applicable payment processing fees imposed by a third-party payment processor, (ii) any applicable taxes withheld pursuant to these Terms, and (iii) a service and platform fee in the amount set forth on the pricing page, which is retained by Whop. You understand and agree that the entire purchase price (not just the net amount paid to you) must be immediately returned or refunded if requested by Whop or upon your violation of these Terms, and you agree that Whop or any payment processor acting on its behalf may process such return or refund.</li>
            <li><b>Whop Credits</b>. You will be able to view all amounts owed to you in the form of “<b>Whop Credits</b>” on your Whop account. Whop Credits represent funds held in an account owned and controlled by you with a third-party service provider or payment processor, such as Stripe. The funds underlying Whop Credits may be used to purchase Products and (other than with respect to Dropped Whop Credits) may be converted to the equivalent amount of U.S. Dollars and withdrawn by you through your account with the third party service provider or payment processor. Whop Credits are not themselves transferrable. Whop Credits do not represent cash or funds held by Whop on your behalf and have no cash value, other than as held in your account with the third party payment processor. You understand and agree that Whop Credits may be withdrawn from your account as required in payment of purchases you make; as fines, fees, or assessments for your violation of these Terms or the terms of any agreement with a third party payment process; as required by law; or as required by our third party payment processor. You further agree to provide any information, execute any agreements or other documents, and verify your identity with Whop or its third party payment processor and understand and agree that failure to do so may terminate your Whop Credits.&nbsp;</li>
            <li><b>Subscription Service</b>. The Service may include certain subscription-based Products, or certain aspects of the Service itself may result in automatically recurring payments for periodic charges (“<b>Subscription Products</b>” and such charges, the “<b>Subscription Fee</b>”). The “<b>Subscription Billing Date</b>” is the date when you purchase your first subscription to the Subscription Product. Your access to the Subscription Product will begin on the Subscription Billing Date and continue for the subscription period specified when you make your purchase (such period, the “<b>Initial Subscription Period</b>”). Some subscriptions may automatically renew for additional periods if specified in the Subscription Product description (the Initial Subscription Period and each such renewal period, each a “<b>Subscription Period</b>”) unless you cancel the Subscription Product or the Seller or we terminate it. If you activate a Subscription Product, then you authorize Whop or its third-party payment processors to save, store, or otherwise maintain the payment method you have provided for the Subscription Product and periodically charge such payment method, on a going-forward basis and until cancellation of the Subscription Product, for all accrued sums on or before the payment due date. If you use a debit card or your bank account as your chosen payment method, you agree to enter into this separate debit authorization form and retain a copy for your records. Your account will be charged automatically on the Subscription Billing Date and thereafter on the renewal date of your Subscription Product for all applicable fees and taxes for the next Subscription Period. You must cancel your Subscription Product before it renews unless otherwise specified in the Subscription Product’s description in order to avoid billing of the next periodic Subscription Fee to your account. Whop or its third-party payment processor will bill the periodic Subscription Fee to the payment method associated with your account or that you otherwise provide to us. You may cancel the Subscription Product by following the cancellation steps described in the product description or by contacting us at support@whop.com. YOUR CANCELLATION MUST BE RECEIVED BEFORE THE RENEWAL DATE IN ORDER TO AVOID CHARGE FOR THE NEXT SUBSCRIPTION PERIOD.</li>
            <li><b>Delinquent Accounts</b>. Whop may suspend or terminate access to the Service or any Product, for any account for which any amount is due but unpaid. In addition to the amount due for the Service, a delinquent account will be charged with fees or charges that are incidental to any chargeback or collection of any of the unpaid amount, including collection fees. If your payment method is no longer valid at the time a renewal Subscription Fee is due, then Whop reserves the right to delete your account and any information or User Content (defined below) associated with your account without any liability to you.&nbsp;&nbsp;</li>
            <li><b>High Chargebacks, Returns, or Other Negative Metrics. </b>If you or your account are subject to a high level of chargebacks, returns, refund requests, payment network imposed fines, fees, or assessments, or we are otherwise required to do so by our third party payment processor, we have the right to pass any such fines, fees, or assessments on to you and/or terminate your account and access to the Service, in our sole discretion. You remain solely liable for all chargebacks, returns, or refunds. In the event we have reason to believe that your account is engaged in fraudulent or other unauthorized activity, you agree that, in addition to any other remedies set forth in these Terms, we have the right to reverse any payments made to you by our payment processor without notice to you and you agree that you are solely responsible for any such fraudulent activity.</li>
            <li>
               <b>Regulatory Matters; Account Termination/Suspension; Regulatory Reviews; Violation of Terms</b>
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>Whop is not a financial institution. Whop is required to comply with the following requirements as part of its own compliance policies, as well as due to commitments and relationships it has with various third parties, including banks, payment processors, and other financial institutions with which it works.</li>
                  <li>Whop reserves the right, in its sole discretion to suspend or terminate any account opened by a Buyer or Seller.</li>
                  <li>Without limiting the generality of the foregoing, Whop may, in its sole discretion or as directed by law enforcement, regulatory agency, or any financial institution or third-party payment processor with which it works, suspend or place a hold on an account. Any suspension or hold on an account may delay the settlement or distribution of any funds owed to a Seller that is associated with such account. In the event that Whop suspends or holds an account pursuant to this provision, it will do so for no longer than is commercially reasonable, and in no event longer than one hundred eight (180) days; provided, however, that in the event that such suspension or hold on an account is directed by law enforcement, regulatory agency, or any financial institution or third-party payment processor with which Whop works, then such suspension or hold shall remain in place for so long as Whop is directed by such party.</li>
                  <li>To the extent reasonable to do so, and if permitted by law or the instructions of any third-party, Whop will provide you with prior notice of the termination or suspension of your account. However, Whop shall have the right to terminate or suspend your account without notice upon your violation of these Terms or if Whop has reason to believe there is fraud or unauthorized use associated with your account.</li>
                  <li>Without limiting anything in the foregoing, Whop may suspend or pause your account while performing any applicable or necessary regulatory reviews being conducted by Whop or its financial institution or payment processing partners.</li>
               </ol>
            </li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>5. Licenses</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Limited License</b>. Subject to your complete and ongoing compliance with these Terms, Whop grants you, exclusively for your personal use, a time limited, non-exclusive, non-transferable, non-sublicensable, revocable license to: (a) install and use one object code copy of any mobile or other downloadable application associated with the Service (whether installed by you or pre installed on your mobile device by the device manufacturer or a wireless telephone provider) on a mobile device that you own or control; and (b) access and use the Service. The foregoing license does not include a license to any Products, which will be granted by the applicable Seller, if at all.&nbsp;</li>
            <li><b>License Restrictions</b>. Except and solely to the extent such a restriction is impermissible under applicable law, you may not: (a) reproduce, distribute, publicly display, publicly perform, or create derivative works of the Service; (b) make modifications to the Service; or (c) interfere with or circumvent any feature of the Service, including any security or access control mechanism. If you are prohibited under applicable law from using the Service, then you may not use it.&nbsp;</li>
            <li><b>Feedback</b>. We respect and appreciate the thoughts and comments from our users. If you choose to provide input and suggestions regarding existing functionalities, problems with or proposed modifications or improvements to the Service (“<b>Feedback</b>”), then you hereby grant Whop an unrestricted, perpetual, irrevocable, non-exclusive, fully-paid, royalty-free right and license to exploit the Feedback in any manner and for any purpose, including to improve the Service and create other products and services. We will have no obligation to provide you with attribution for any Feedback you provide to us.<b>&nbsp;</b></li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>6. Ownership; Proprietary Rights</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">The Service is owned and operated by Whop. The visual interfaces, graphics, design, compilation, information, data, computer code (including source code or object code), software, services, and all other elements of the Service, but excluding any Products, provided by Whop (“<b>Materials</b>”) are protected by intellectual property and other laws. All Materials included in the Service are the property of Whop or its third-party licensors. Except as expressly authorized by Whop, ∂you may not make use of the Materials. There are no implied licenses in these Terms and Whop reserves all rights to the Materials not granted expressly in these Terms.&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>7. Third-Party Terms</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Third-Party Services and Linked Websites</b>. Whop may provide tools through the Service that enable you to export information, including User Content, to third-party services, including through features that allow you to link your account on the Service with an account on the third-party service, such as Twitter or Facebook, or through our implementation of third-party buttons (such as “like” or “share” buttons). By using one of these tools, you hereby authorize that Whop to transfer that information to the applicable third-party service. Third-party services are not under Whop’s control, and, to the fullest extent permitted by law, Whop is not responsible for any third-party service’s use of your exported information. The Service may also contain links to third-party websites. Linked websites are not under Whop’s control, and Whop is not responsible for their content. Further, Whop will not provide exports of third-party data (i.e. Stripe Express accounts) because the option to link to owned data that is readily accessible is already available. Please be sure to review the terms of use and&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>privacy policy</u></a>&nbsp;of any third-party services before you share any User Content or information with such third party services. Once sharing occurs, Whop will have no control over the information that has been shared.&nbsp;<b>&nbsp;</b></li>
            <li><b>Third-Party Software</b>. The Service may include or incorporate third-party software components that are generally available free of charge under licenses granting recipients broad rights to copy, modify, and distribute those components (“<b>Third-Party Components</b>”). Although the Service is provided to you subject to these Terms, nothing in these Terms prevents, restricts, or is intended to prevent or restrict you from obtaining Third-Party Components under the applicable third-party licenses or to limit your use of Third-Party Components under those third party licenses.<b>&nbsp;</b></li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>8. User Content&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>User Content Generally</b>. Certain features of the Service may permit users to submit, upload, publish, broadcast, or otherwise transmit (“<b>Post</b>”) content to the Service, including Product images, descriptions, reviews, and any other works of authorship or other works (“<b>User Content</b>”). You retain any copyright and other proprietary rights that you may hold in the User Content that you Post to the Service, subject to the licenses granted in these Terms.&nbsp;</li>
            <li><b>Limited License Grant to Whop</b>. By Posting User Content to or via the Service, you grant Whop a worldwide, non-exclusive, royalty-free, fully paid right and license (with the right to sublicense through multiple tiers) to host, store, transfer, publicly display, publicly perform (including by means of a digital audio transmission), communicate to the public, reproduce, modify for the&nbsp;purpose of formatting for display, create derivative works as authorized in these Terms, and distribute your User Content, in whole or in part, in any media formats and through any media channels, in each instance whether now known or hereafter developed. You agree to pay all monies owing to any person or entity resulting from Posting your User Content and from Whop’s exercise of the license set forth in this Section.&nbsp;</li>
            <li>
               <b>You Must Have Rights to the Content You Post; User Content Representations and Warranties</b>. You must not Post User Content if you are not the owner of or are not fully authorized to grant rights in all of the elements of that User Content. Whop disclaims any and all liability in connection with User Content. You are solely responsible for your User Content and the consequences of providing User Content via the Service. By providing User Content via the Service, you affirm, represent, and warrant to us that:&nbsp;
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>you are the sole author, creator, and owner of the User Content and intellectual property and proprietary rights thereto, or have the necessary licenses, rights, consents, and permissions to authorize Whop and users of the Service to use and distribute your User Content as necessary to exercise the licenses granted by you in this Section, in the manner contemplated by Whop, the Service, and these Terms;&nbsp;</li>
                  <li>your User Content is honest, truthful, and accurate to the best of your knowledge;</li>
                  <li>your User Content, and the Posting or other use of your User Content as contemplated by these Terms, does not and will not: (i) infringe, violate, misappropriate, or otherwise breach any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property, contract, or proprietary right; (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; (iii) violate any confidentiality, non-disclosure, or contractual obligations you might have towards a third party, including without limitation your current or former employer; or (iv) violate or cause Whop to violate any law or regulation or require us to obtain any further licenses from or pay any royalties, fees, compensation or other amounts or provide any attribution to any third parties;&nbsp;</li>
                  <li>your User Content could not be deemed by a reasonable person to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate; and</li>
                  <li>when your User Content consists of an endorsement, review, or evaluation of Whop, a Seller, a product, service, or third party (“<b>Reviews and Endorsements</b>”), you further represent and warrant that:&nbsp;</li>
               </ol>
            </li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full">(a) unless you prominently disclose your affiliation and interest in such endorsed, reviewed, or evaluated company, Whop, Seller, product, service, or third party you (i) are not an employee, contractor, agent, officer or director of the party, product, or service for which you are submitting an endorsement, review, evaluation or opinion (collectively “Vendor”) (ii) you are not a competitor of such Vendor that offers a competitive product or service (“Competitor”), and (iii) otherwise have no pecuniary interest in or material connection to such Vendor, Competitor or their product or service;&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">(b) your review does not disclose any confidential information;&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">(c) you are a bona fide user of the Vendor, product, or service referenced in your Reviews and Endorsements;&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">(d) the opinions expressed in your Reviews and Endorsements are your individual honest opinions, findings, beliefs, and experiences with respect to the Vendor, product, or service; and&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">(e) the statements made in the Reviews and Endorsements are not false or misleading in any aspect.&nbsp;</p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li>
               <b>Reviews and Endorsements</b>. The following additional terms apply to any User Content that includes Reviews and Endorsements:
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>You may not post or submit group, team, multi-authored, or technology-authored Reviews and Endorsements;</li>
                  <li>Your Reviews and Endorsements must provide honest and accurate views, opinions, findings, beliefs, and/or experiences, they must not contain any false, misleading, or unsubstantiated information about the Vendor, products, or services, or otherwise;</li>
                  <li>You must clearly and conspicuously disclose any material connections you have with a Vendor or their product or service referenced in your User Content - a material connection is one that could influence the weight or credibility another person would give to your opinions, evaluations, reviews, ratings, messages, or comments, such as employment or independent contractor relationship, receipt of free or discounted products or services, an affiliate marketing relationship, receipt of payment or other consideration or material benefit from a Vendor;</li>
                  <li>Submission of previously published opinions, evaluations, reviews, ratings, messages, or comments is prohibited; and</li>
                  <li>Seller providing users with an incentive to post Reviews and Endorsements on the Whop platform about Sellers or their products or services are responsible for (a) informing such users of their obligations under these Terms with respect to such Reviews and Endorsements, including without limitation their obligations in this Section 8.4, (b) monitoring and correcting such Reviews and Endorsements as needed, and (c) reporting non-compliant Reviews and Endorsements to support@whop.com.</li>
               </ol>
            </li>
            <li><b>User Content Disclaimer</b>. We are under no obligation to edit or control User Content that you or other users Post and will not be in any way responsible or liable for User Content. Whop may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in our sole judgment violates these Terms, is alleged to violate the rights of third parties, or is otherwise objectionable. You understand that, when using the Service, you will be exposed to User Content from a variety of sources and acknowledge that User Content may be inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you have or may have against Whop with respect to User Content. If notified by a user or content owner that User Content allegedly does not conform to these Terms, we may investigate the allegation and determine in our sole discretion whether to remove the User Content, which we reserve the right to do at any time and without notice. For clarity, Whop does not permit infringing activities on the Service.&nbsp;</li>
            <li><b>Monitoring Content</b>. Whop does not control and does not have any obligation to monitor: (a) User Content; (b) any content made available by third parties; or (c) the use of the Service by its users. You acknowledge and agree that Whop reserves the right to, and may from time to time, monitor any and all information transmitted or received through the Service for operational and other purposes. If at any time Whop chooses to monitor the content, then Whop still assumes no responsibility or liability for content or any loss or damage incurred as a result of the use of content. During monitoring, information may be examined, recorded, copied, and used in accordance with our&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>Privacy Policy</u></a>. Whop may block, filter, mute, remove or disable access to any User Content uploaded to or transmitted through the Service without any liability to the user who Posted such User Content to the Service or to any other users of the Service.&nbsp;&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>9. Communications&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Push Notifications</b>. When you install our app on your mobile device, you agree to receive push notifications, which are messages an app sends you on your mobile device when you are not in the app. You can turn off notifications by visiting your mobile device’s “settings” page.&nbsp;</li>
            <li><b>Email</b>. We may send you emails concerning our products and services, as well as those of third parties. You may opt out of promotional emails by following the unsubscribe instructions in the promotional email itself.&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>10. Prohibited Conduct</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">BY USING THE SERVICE, YOU AGREE NOT TO:&nbsp;</p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li>use the Service or sell any Products for any illegal purpose or in violation of any local, state, national, or international law;&nbsp;</li>
            <li>use the Service to sell any alcohol, drugs, substances designed to mimic alcohol or drugs, or equipment designed for making or using alcohol or drugs;</li>
            <li>use the Service to sell tickets that are search for, reserved, or purchased using ticket bot technology or automated ticket purchasing software;</li>
            <li>use the Service to sell any Products that a reasonable person might deem to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate;</li>
            <li>sell, rent, leak, disclose, or transfer data or information that you acquire via the Service from a Seller, whether such sale, rental, leak, disclosure or transfer by you occurs on the Service or elsewhere;</li>
            <li>violate, encourage others to violate, or provide instructions on how to violate, any right of a third party, including by infringing or misappropriating any third-party intellectual property or proprietary right;&nbsp;</li>
            <li>access, search, or otherwise use any portion of the Service through the use of any engine, software, tool, agent, device, or mechanism (including spiders, robots, crawlers, and data mining tools) other than the software or search agents provided by Whop;&nbsp;</li>
            <li>interfere with security-related features of the Service, including by: (i) disabling or circumventing features that prevent or limit use, printing or copying of any content; or (ii) reverse engineering or otherwise attempting to discover the source code of any portion of the Service except to the extent that the activity is expressly permitted by applicable law;&nbsp;</li>
            <li>
               interfere with the operation of the Service or any user’s enjoyment of the Service, including by:
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>(i) uploading or otherwise disseminating any virus, adware, spyware, worm, or other malicious code;</li>
                  <li>(ii) making any unsolicited offer or advertisement to another user of the Service;</li>
                  <li>(iii) collecting personal information about another user or third party without consent; or</li>
                  <li>(iv) interfering with or disrupting any network, equipment, or server connected to or used to provide the Service</li>
                  <li>(v) harassing any user with unsolicited, unwelcome, disrespectful, physically abusive or offensive behavior. Examples of harassment include, but are not limited to, user targeting attempts (social media bans, server bans, attacking other users’ social media), unwanted comments or remarks, jokes, slurs, online messages, unwanted physical intimidation or touch and literature including pictures and posters, depicting people in a negative light based on prohibited grounds, e.g. racial or religious harassment, age harassment, etc.</li>
               </ol>
            </li>
            <li>perform any fraudulent activity including impersonating any person or entity, claiming a false affiliation or identity, accessing any other Service account without permission;&nbsp;</li>
            <li>sell or otherwise transfer the access granted under these Terms or any Materials (as defined in Section 6) or any right or ability to view, access, or use any Materials; or&nbsp;</li>
            <li>attempt to do any of the acts described in this Section 10 or assist or permit any person in engaging in any of the acts described in this Section 10.&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">The list of prohibitions in this Section 10 provides examples and is not complete or exclusive. Whop may, at its sole discretion, terminate these Terms or your account on the Service, or suspend or terminate your access to the Service, at any time for any reason or no reason, with or without notice, and without any liability to you arising from such termination.&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>11. Intellectual Property Rights Protection&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Respect of Third Party Rights</b>. Whop respects the intellectual property rights of others, takes the protection of intellectual property rights very seriously, and asks users of the Service to do the same. Infringing activity will not be tolerated on or through the Service.&nbsp;</li>
            <li><b>DMCA Notification</b>. We comply with the provisions of the Digital Millennium Copyright Act applicable to Internet service providers (17 U.S.C. § 512, as amended). If you have an intellectual property rights related complaint about any material on the Service, you may contact our Designated Agent at the following address:&nbsp; Whop, Inc.&nbsp; Attention: Legal (IP Notification)&nbsp;at 10 Grand Street 13A, Brooklyn, NY 11249&nbsp;(email: legal@whop.com&nbsp;)</li>
            <li>
               <b>Procedure for Reporting Claimed Infringement</b>. If you believe that any content made available on or through the Service has been used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a written “<b>Notification of Claimed Infringement</b>” to the Designated Agent identified above containing the following information:&nbsp;
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed;&nbsp;</li>
                  <li>a description of the copyrighted work or other intellectual property right that you claim has been infringed;&nbsp;</li>
                  <li>a description of the material that you claim is infringing and where it is located on the Service;&nbsp;</li>
                  <li>your address, telephone number, and email address;&nbsp;</li>
                  <li>a statement by you that you have a good faith belief that the use of the materials on the Service of which you are complaining is not authorized by the copyright or other intellectual property right owner, its agent, or the law; and&nbsp;</li>
                  <li>a statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright or other intellectual property right owner or authorized to act on the copyright or intellectual property owner’s behalf. Your Notification of Claimed Infringement may be shared by Whop with the user alleged to have infringed a right you own or control as well as with the operators of publicly available databases that track notifications of claimed infringement, and you consent to Whop making such disclosures. You should consult with your own lawyer or see 17 U.S.C. § 512 to confirm your obligations to provide a valid notice of claimed infringement.&nbsp;</li>
               </ol>
            </li>
            <li><b>Repeat Infringers</b>. Whop’s policy is to: (a) remove or disable access to material that Whop believes in good faith, upon notice from an intellectual property rights owner or authorized agent, is infringing the intellectual property rights of a third party by being made available through the Service; and (b) in appropriate circumstances, to terminate the accounts of and block access to the Service by any user who repeatedly or egregiously infringes other people’s copyright or other intellectual property rights. Whop will terminate the accounts of users that are determined by Whop to be repeat infringers. Whop reserves the right, however, to suspend or terminate accounts of users in our sole discretion.&nbsp;&nbsp;&nbsp;</li>
            <li>
               <b>Counter Notification</b>. If you receive a notification from Whop that material made available by you on or through the Service has been the subject of a Notification of Claimed Infringement, then you will have the right to provide Whop with what is called a “<b>Counter Notification</b>.” To be effective, a Counter Notification must be in writing, provided to Whop’s Designated Agent through one of the methods identified in Section 11.2, and include substantially the following information:&nbsp;
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>your physical or electronic signature;&nbsp;</li>
                  <li>identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;&nbsp;</li>
                  <li>a statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and&nbsp;</li>
                  <li>your name, address, and telephone number, and a statement that you consent to the jurisdiction of Federal District Court for the judicial district in which the address is located, or if you are residing outside of the United States, then for any judicial district in which Whop may be found, and that you will accept service of process from the person who provided notification under Section 11.2 above or an agent of that person.&nbsp; A party submitting a Counter Notification should consult a lawyer or see 17 U.S.C. § 512 to confirm the party’s obligations to provide a valid counter notification under the Copyright Act.&nbsp;</li>
               </ol>
            </li>
            <li><b>Reposting of Content Subject to a Counter Notification</b>. If you submit a Counter Notification to Whop in response to a Notification of Claimed Infringement, then Whop will promptly provide the person who provided the Notification of Claimed Infringement with a copy of your Counter Notification and inform that person that Whop will replace the removed User Content or cease disabling access to it in 10 business days, and Whop will replace the removed User Content and cease disabling access to it not less than 10, nor more than 14, business days following receipt of the Counter Notification, unless Whop’s Designated Agent receives notice from the party that submitted the Notification of Claimed Infringement that such person has filed an action seeking a court order to restrain the user from engaging in infringing activity relating to the material on Whop’s system or network.</li>
            <li>
               <b>False Notifications of Claimed Infringement or Counter Notifications</b>. The Copyright Act provides at 17 U.S.C. § 512(f) that: “[a]ny person who knowingly materially misrepresents under [Section 512 of the Copyright Act (17 U.S.C. § 512)]
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>(1) that material or activity is infringing, or&nbsp;</li>
                  <li>(2) that material or activity was removed or disabled by mistake or misidentification, will be liable for any damages, including costs and attorneys’ fees, incurred by the alleged infringer, by any copyright owner or copyright owner’s authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [Whop] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it.” Whop reserves the right to seek damages from any party that submits a Notification of Claimed Infringement or Counter Notification in violation of the law.&nbsp;</li>
               </ol>
            </li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>12. Affiliate Program</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Overview</b>. The Whop Affiliate Program ( “Affiliate Program”) allows affiliate participants (“Affiliates”) to earn Whop Credits by either (a) referring prospective customers to purchase products or services hosted on the Whop platform (“Buyer Program Affiliates”), or (b) referring prospective merchants to join Whop as a Seller (“Seller Program Affiliates”). Participation in the Affiliate Program is only open to individuals aged 18 years or older who are legal residents of and residing in the United States. Prospective Affiliates must complete an application and be approved by Whop to become an Affiliate. Once Whop reviews and approves a prospective Affiliate’s application, the Affiliate will receive a unique tracking link to place on their website or promote through other channels (“Affiliate Link”).</li>
            <li><b>Affiliate Marketing Activities</b>. Affiliate agrees to use reasonable, good-faith efforts to provide affiliate services to Whop through referring and promoting Whop and applicable Whop Sellers’ and their products and services on the Whop Platform in the United States in accordance with the Terms, including these Affiliate Program terms. Affiliate represents, warrants and covenants that Affiliate will perform such services in a professional and workmanlike manner and that such services will comply with the requirements set forth hereunder, including in any documentation, guidelines, policies, and specifications referenced herein, which are all incorporated herein by reference.</li>
            <li><b>Affiliate Compensation. </b>Affiliate compensation depends on the type of affiliate marketing Affiliate conducts:</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><u>Seller Program Affiliates</u> – Affiliates can earn rewards for referring new merchants to the Whop Platform. For users who join Whop as a Seller for the first time via the Affiliate’s Affiliate Link (“Referred Sellers”), as reasonably determined by Whop, Whop will pay the Affiliate an amount equal to a percentage of Whop’s net revenue from the Referred Seller, for the first six (6) months after the date when the Referred Seller joined Whop. Affiliate commissions cease after the end of the six month period.&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><u>Buyer Program Affiliates</u> - Affiliates can earn rewards for referring users who make purchases from Sellers on the Whop platform. Either Whop, or Sellers, can determine and disclose the fee or percentage a Buyer Program Affiliate will receive when a purchase of the Seller’s products or services is made via an Affiliate’s Affiliate Link (“Affiliate Offer”). For each purchase of Seller’s products or services made via the Affiliate’s Affiliate Link, as reasonably determined by Whop, Whop shall pay Affiliate for such qualifying sale according to the Affiliate Offer. Affiliate Offers are subject to change from time to time and may be terminated at any time. Such changes and terminations are effective immediately. The Affiliate Offer at the time of qualifying sale applies. Please check Affiliate Offers periodically for any changes or termination.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">Affiliate is solely responsible for promoting use of its Affiliate Link, and Whop shall not be responsible for any users’ failure to utilize an Affiliate Link in the registration or purchasing process, and such failure of use will result in lack of attribution of sale to Affiliate. Each party will be responsible, as required under applicable law, for identifying and paying all taxes and other governmental fees and charges (and any penalties, interest, and other additions thereto) that are imposed on that party upon or with respect to the transactions and payments received by it under these Affiliate Program terms. Each party will bear all costs and expenses incurred by it in connection with its business and the performance of its obligations under these Affiliate Program terms and in no event will Whop be obligated to reimburse Affiliate for any costs incurred by providing services hereunder.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Independent Contractors. </b>The relationship between Whop and Affiliate established by these Affiliate Program terms is that of independent contractors. Neither execution nor performance of the Terms including the Affiliate Program terms shall be construed to have established any joint venture, partnership, or employment relationship between the parties.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Limited Trademark License for Affiliates.</b>&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">Subject to these Terms (including without limitation the trademark provisions therein), Whop hereby grants to Affiliate a non-exclusive, revocable, non-sublicensable, non-transferable right and license to use and display Whop’s trademark “WHOP” (the “<b>Licensed Marks</b>”) in the United States in accordance with any trademark usage guidelines specified by Whop, and in accordance with further provisions in the Terms, solely in connection with promoting the Whop platform to new merchants as a Seller Program Affiliate or in connection with promoting Sellers’ product and services on the Whop platform as a Buyer Program Affiliate.&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">The purchase of keywords, engaging in PPC bidding, and otherwise engaging in paid promotions with keywords, on the following keywords, or misspellings of these, is strictly prohibited: Whop, Whop discount, Whop coupon, either alone or in combination with other terms or keywords. Use of any Whop-related keywords through paid advertising requires prior approval from a Whop Affiliate Program manager, which may be granted, denied, or conditioned at Whop’s sole and absolute discretion.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Requirements. </b>By participating in the Affiliate Program, Affiliates agree that:&nbsp;</p>
         <ul class="text-paragraph2 text-whop-black list-inside list-disc pl-4">
            <li>They will at all times present Whop, its products and services, Sellers, and Seller’s products and services in an honest and truthful manner, in a manner that reflects their actual experience, will not make any misrepresentations, and will otherwise remain compliant with the <a href="https://www.federalregister.gov/documents/2023/07/26/2023-14795/guides-concerning-the-use-of-endorsements-and-testimonials-in-advertising" class="text-whop-primary underline"><u>FTC’s Endorsement Guidelines</u></a>.</li>
            <li>they will disclose in a clear and conspicuous manner near the Affiliate Link that they will receive compensation if someone makes a purchase or transaction through their link;</li>
            <li>their website and other promotional channels in connection with participating in the Affiliate Program do not contain or promote (a) violations of copyright, trademark, publicity, or other intellectual property or proprietary rights, (b) adult, violent and defamatory content, (c) religious or political viewpoints; (d) content or services that violate the law; or false or misleading advertising;</li>
            <li>they will strictly comply with any Affiliate Program participation guidelines specified by Whop; and</li>
            <li>they will not purchase keywords, engage in PPC bidding or other paid promotions with keywords, on the following keywords, or misspellings of these: Whop, Whop discount, Whop coupon, either alone or in combination with other terms or keywords, unless they have obtained prior written approval from a Whop Affiliate Program manager, which may be granted, denied, or conditioned at Whop’s sole and absolute discretion.&nbsp;</li>
         </ul>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Termination.</b> Failure to comply with these terms of the Affiliate Program or other Terms, may result in immediate termination and withholding or clawback of Whop Credits and/or payments. Whop may terminate Affiliate’s participation in the Affiliate Program immediately at any time for any or no reason by giving Affiliate notice of such termination, or if Whop terminates or otherwise ceases to offer the Affiliate Program. Affiliate may terminate Affiliate’s participation in the Affiliate Program immediately at any time for any or no reason by giving Whop notice of such termination. Upon termination of Affiliate’s participation in the Affiliate Program, Affiliate will (i) immediately cease to represent itself as a marketing affiliate of Whop; (ii) immediately take down any posted promotional materials and cease all active promotion of Whop and any applicable products or services on the Whop platform; (iii) immediately cease to use or distribute any Affiliate Links; and (iv) immediately cease using any Licensed Marks. Affiliate will cease to earn Whop Credits immediately upon termination of Affiliate’s participation in the Affiliate Program. Within thirty (30) days of termination of Affiliate’s participation in the Affiliate Program, Whop will deposit payment in the form of Whop Credits for all qualified transactions up to the date of termination. Affiliate must maintain a Whop Credit account for at least sixty (60) days after termination of Affiliate’s participation in the Affiliate Program in order to facilitate such compensation.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Disclaimer.</b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">WHOP DOES NOT WARRANT OR GUARANTEE ANY MINIMUM LEVEL OF COMMISSIONS, WHOP CREDITS, OR PAYMENTS THAT WILL BE ACHIEVED BY AFFILIATE HEREUNDER. WHOP EXPRESSLY DISCLAIMS, TO THE FULLEST EXTENT PERMITTED BY LAW, ALL REPRESENTATIONS AND WARRANTIES REGARDING THE AFFILIATE PROGRAM, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>13. Modification of Terms</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">We may, from time to time, change these Terms. Please check these Terms periodically for changes. Revisions will be effective immediately except that, for existing users, material revisions will be effective 30 days after posting or notice to you of the revisions unless otherwise stated. We may require that you accept modified Terms in order to continue to use the Service.&nbsp; If you do not agree to the modified Terms, then you should remove your User Content and discontinue your use of the Service. Except as expressly permitted in this Section 13, these Terms may be amended only by a written agreement signed by authorized representatives of the parties to these Terms.&nbsp;&nbsp;</p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>14. Term, Termination, and Modification of the Service&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Term</b>. These Terms are effective beginning when you accept the Terms or first download, install, access, or use the Service, and ending when terminated as described in Section 14.2.&nbsp;</li>
            <li><b>Termination</b>. If you violate any provision of these Terms, then your authorization to access the Service and these Terms automatically terminate. In addition, Whop may, at its sole discretion, terminate these Terms or your account on the Service, or suspend or terminate your access to the Service, at any time for any reason or no reason, with or without notice, and without any liability to you arising from such termination. You may terminate your account and these Terms at any time by using the live chat feature on the Service or by contacting customer service at support@whop.com.&nbsp;</li>
            <li><b>Effect of Termination</b>. Upon termination of these Terms: (a) your license rights will terminate and you must immediately cease all use of the Service; (b) you will no longer be authorized to access your account or the Service; (c) you must pay Whop any unpaid amount that was due prior to termination; (d) you may lose access to certain Products managed by Whop, and (e) all payment obligations accrued prior to termination and Sections 5.3, 6, 14.3, 15, 16, 17, 18, and 19 will survive. You are solely responsible for retaining copies of any User Content you Post to the Service since upon termination of your account, you may lose access rights to any User Content you Posted to the Service. If your account has been terminated for a breach of these Terms, then you are prohibited from creating a new account on the Service using a different name, email address or other forms of account verification.<b>&nbsp;</b></li>
            <li><b>Modification of the Service</b>. Whop reserves the right to modify or discontinue all or any portion of the Service at any time (including by limiting or discontinuing certain features of the Service), temporarily or permanently, without notice to you. Whop will have no liability for any change to the Service, including any paid-for functionalities of the Service,&nbsp;or any suspension or termination of your access to or use of the Service. You should retain copies of any User Content&nbsp;you Post to the Service so that you have permanent copies in the event the Service is modified in such a way that you lose access to User Content you Posted to the Service.<b>&nbsp;</b></li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>15. Indemnity</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">To the fullest extent permitted by law, you are responsible for your use of the Service, and you will defend and indemnify Whop, its affiliates and their respective shareholders, directors, managers, members, officers, employees, consultants, and agents (together, the “<b>Whop Entities</b>”) from and against every claim brought by a third party, and any related liability, damage, loss, and expense, including attorneys’ fees and costs, arising out of or connected with: (1) your unauthorized use of, or misuse of, the Service or any Product; (2) your violation of any portion of these Terms, any representation, warranty, or agreement referenced in these Terms, or any applicable law or regulation; (3) your violation of any third-party right, including any intellectual property right or publicity, confidentiality, other property, or privacy right; (4) any dispute regarding any Product, or (5) any dispute or issue between you and any third party. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (without limiting your indemnification obligations with respect to that matter), and in that case, you agree to cooperate with our defense of those claims.<b>&nbsp;</b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>16. Disclaimers; No Warranties by Whop&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li>THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE ARE&nbsp;PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS. WHOP DISCLAIMS ALL WARRANTIES OF&nbsp;ANY KIND, WHETHER EXPRESS OR IMPLIED, RELATING TO THE SERVICE AND ALL MATERIALS&nbsp;AND CONTENT AVAILABLE THROUGH THE SERVICE, INCLUDING: (A) ANY IMPLIED WARRANTY OF&nbsp;MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; AND (B) ANY WARRANTY ARISING OUT OF COURSE OF DEALING, USAGE, OR&nbsp;TRADE. WHOP DOES NOT WARRANT THAT THE SERVICE OR ANY PORTION OF THE SERVICE, OR&nbsp;ANY MATERIALS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND WHOP DOES NOT WARRANT THAT ANY OF THOSE ISSUES WILL BE CORRECTED.&nbsp;</li>
            <li>ALL PRODUCTS ARE PROVIDED SOLELY BY THE APPLICABLE SELLER, ANY PURCHASE OR SALE OF PRODUCTS IS ONLY FACILITATED BY WHOP. YOU AGREE THAT WHOP WILL NOT HAVE ANY&nbsp;LIABILITY TO YOU, AND WHOP HEREBY DISCLAIMS ALL SUCH LIABILITY, REGARDING THE USE OR FUNCTION OF ANY PRODUCT. ANY DISPUTES REGARDING A PRODUCT ARE SOLELY BETWEEN THE APPLICABLE BUYER AND SELLER.<b>&nbsp;</b></li>
            <li>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE&nbsp;SERVICE OR WHOP ENTITIES OR ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE&nbsp;SERVICE WILL CREATE ANY WARRANTY REGARDING ANY OF THE WHOP ENTITIES OR THE&nbsp;SERVICE THAT IS NOT EXPRESSLY STATED IN THESE TERMS. WE ARE NOT RESPONSIBLE FOR ANY&nbsp;DAMAGE THAT MAY RESULT FROM THE SERVICE AND YOUR DEALING WITH ANY OTHER SERVICE&nbsp;USER. YOU UNDERSTAND AND AGREE THAT YOU USE ANY PORTION OF THE SERVICE AT YOUR&nbsp;OWN DISCRETION AND RISK, AND THAT WE ARE NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE SERVICE) OR ANY LOSS OF DATA, INCLUDING USER CONTENT.<b>&nbsp;</b></li>
            <li>THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS SECTION 16 APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. Whop does not disclaim any warranty or other right that Whop is prohibited from disclaiming under applicable law.&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>17. Limitation of Liability&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li>TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE WHOP ENTITIES BE LIABLE&nbsp;TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES&nbsp;(INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, OR ANY OTHER INTANGIBLE LOSS)&nbsp;ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS&nbsp;OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE SERVICE, WHETHER BASED ON&nbsp;WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY WHOP ENTITY HAS BEEN INFORMED OF THE POSSIBILITY OF DAMAGE.&nbsp;</li>
            <li>
               EXCEPT AS PROVIDED IN SECTIONS 18.5 AND 18.6 AND TO THE FULLEST EXTENT PERMITTED BY LAW, THE AGGREGATE LIABILITY OF THE WHOP ENTITIES TO YOU FOR ALL CLAIMS ARISING OUT&nbsp;OF OR RELATING TO THE USE OF OR ANY INABILITY TO USE ANY PORTION OF THE SERVICE OR&nbsp;OTHERWISE UNDER THESE TERMS, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED&nbsp;TO THE GREATER OF:
               <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
                  <li>(A) THE AMOUNT YOU HAVE PAID TO WHOP FOR ACCESS TO AND USE OF THE SERVICE IN THE 12 MONTHS PRIOR TO THE EVENT OR CIRCUMSTANCE GIVING RISE TO THE CLAIM AND</li>
                  <li>(B) US$100.&nbsp;</li>
               </ol>
            </li>
            <li>EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES&nbsp;ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER THESE TERMS. THIS ALLOCATION IS AN&nbsp;ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION 17 WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.&nbsp;</li>
            <li>YOU AND WHOP AGREE THAT YOU MUST INITIATE ANY PROCEEDING OR ACTION WITHIN ONE (1) YEAR OF THE DATE OF THE OCCURRENCE OF THE EVENT OR FACTS GIVING RISE TO A DISPUTE THAT IS ARISING OUT OF OR RELATED TO THESE TERMS. OTHERWISE, YOU FOREVER WAIVE THE RIGHT TO PURSUE ANY CLAIM OR CAUSE OF ACTION, OF ANY KIND OR CHARACTER, BASED ON SUCH EVENTS OR FACTS, AND SUCH CLAIM(S) OR CAUSE(S) OF ACTION ARE PERMANENTLY BARRED.</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>18. Dispute Resolution and Arbitration&nbsp;</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND WHOP ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.&nbsp;</p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Generally</b>. Except as described in Section 18.2 and 18.3, you and Whop agree that every dispute arising in connection with these Terms, the Service, or communications from us will be resolved through binding arbitration. Arbitration uses a neutral arbitrator instead of a judge or jury, is less formal than a court proceeding, may allow for more limited discovery than in court, and is subject to very limited review by courts. This agreement to arbitrate disputes includes all claims whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms. Any dispute&nbsp;relating to the interpretation, applicability, or enforceability of this binding arbitration agreement will be resolved by the arbitrator.&nbsp;</li>
            <li><b>Exceptions</b>. Although we are agreeing to arbitrate most disputes between us, nothing in these Terms will be deemed to waive, preclude, or otherwise limit the right of either party to: (a) bring an individual action in small claims court; (b) pursue an enforcement action through the&nbsp;applicable federal, state, or local agency if that action is available; (c) seek injunctive relief in a court of law in aid of arbitration; or (d) to file suit in a court of law to address an intellectual property infringement claim.&nbsp;</li>
            <li><b>Opt-Out</b>. If you do not wish to resolve disputes by binding arbitration, you may opt out of the provisions of this Section 18 within 30 days after the date that you agree to these Terms by sending a letter to Whop Inc., Attention: Legal Department – Arbitration Opt-Out, 10 Grand St. – Ste. 13A, Brooklyn, NY 11249 that specifies: your full legal name, the email address associated with your account on the Service, and a statement that you wish to opt out of arbitration (“<b>Opt-Out Notice</b>”). Once Whop receives your Opt-Out Notice, this Section 18 will be void and any action arising out of these Terms will be resolved as set forth in Section 19.2. The remaining provisions of these Terms will not be affected by your Opt-Out Notice.&nbsp;</li>
            <li><b>Arbitrator</b>. This arbitration agreement, and any arbitration between us, is subject the Federal Arbitration Act and will be administered by the American Arbitration Association (“<b>AAA</b>”) under its Consumer Arbitration Rules (collectively, “<b>AAA Rules</b>”) as modified by these Terms. The AAA Rules and filing forms are available online at www.adr.org, by calling the AAA at +1-800-7787879, or by contacting Whop.&nbsp;&nbsp;</li>
            <li><b>Commencing Arbitration</b>. Before initiating arbitration, a party must first send a written notice of the dispute to the other party by certified U.S. Mail or by Federal Express (signature required) or, only if that other party has not provided a current physical address, then by electronic mail (“<b>Notice of Arbitration</b>”). Whop’s address for Notice is: Whop Inc., 10 Grand St. – Ste. 13A, Brooklyn, NY 11249. The Notice of Arbitration must: (a) identify the name or account number of the party making the claim; (b) describe the nature and basis of the claim or dispute; and (c) set forth the specific relief sought (“<b>Demand</b>”). The parties will make good faith efforts to resolve the claim directly, but if the parties do not reach an agreement to do so within 30 days after the Notice of Arbitration is received, you or Whop may commence an arbitration proceeding. If you commence arbitration in accordance with these Terms, Whop will reimburse you for your payment of the filing fee, unless your claim is for more than US$10,000 or if the Company has received 25 or more similar demands for arbitration, in which case the payment of any fees will be decided by the AAA Rules. If the arbitrator finds that either the substance of the claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules and the other party may seek reimbursement for any fees paid to AAA.&nbsp;</li>
            <li><b>Arbitration Proceedings</b>. Any arbitration hearing will take place in the county and state of your [residence/billing address] unless we agree otherwise or, if the claim is for US$10,000 or less&nbsp;(and does not seek injunctive relief), you may choose whether the arbitration will be conducted: (a) solely on the basis of documents submitted to the arbitrator; (b) through a telephonic or video hearing; or (c) by an in-person hearing as established by the AAA Rules in the county (or parish) of your [residence/billing address]. During the arbitration, the amount of any settlement offer made by you or Whop must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. Regardless of the manner in which the arbitration is conducted, the arbitrator must issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based.&nbsp;</li>
            <li><b>Arbitration Relief</b>. Except as provided in Section 18.8, the arbitrator can award any relief that would be available if the claims had been brough in a court of competent jurisdiction. If the arbitrator awards you an amount higher than the last written settlement amount offered by Whop before an arbitrator was selected, Whop will pay to you the higher of: (a) the amount awarded by the arbitrator and (b) US$10,000. The arbitrator’s award shall be final and binding on all parties , except (1) for judicial review expressly permitted by law or (2) if the arbitrator's award includes an award of injunctive relief against a party, in which case that party shall have the right to seek judicial review of the injunctive relief in a court of competent jurisdiction that shall not be bound by the arbitrator's application or conclusions of law. Judgment on the award may be entered in any court having jurisdiction.&nbsp;</li>
            <li><b>No Class Actions</b>. YOU AND WHOP AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER&nbsp;ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Whop agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.&nbsp;&nbsp;&nbsp;</li>
            <li><b>Modifications to this Arbitration Provision</b>. If Whop makes any substantive change to this arbitration provision, you may reject the change by sending us written notice within 30 days of the change to Whop’s address for Notice of Arbitration, in which case your account with Whop will be immediately terminated and this arbitration provision, as in effect immediately prior to the changes you rejected will survive.&nbsp;</li>
            <li><b>Enforceability</b>. If Section 18.8 or the entirety of this Section 18 is found to be unenforceable, or if Whop receives an Opt-Out Notice from you, then the entirety of this Section 18 will be null and void and, in that case, the exclusive jurisdiction and venue described in Section 19.2 will govern any action arising out of or related to these Terms.<b>&nbsp;</b>&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>19. Miscellaneous&nbsp;</u></b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>General Terms</b>. These Terms, including the&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>Privacy Policy</u></a>&nbsp;and any other agreements expressly incorporated by reference into these Terms, are the entire and exclusive understanding and agreement between you and Whop regarding your use of the Service. You may not assign or transfer these Terms or your rights under these Terms, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign these Terms and all rights granted under these Terms, including with respect to your User Content, at any time without notice or consent. The failure to require performance of any provision will not affect our right to require performance at any other time after that, nor will a waiver by us of any breach or default of these Terms, or any provision of these Terms, be a waiver of any subsequent breach or default or a waiver of the provision itself. Use of Section headers in these Terms is for convenience only and will not have any impact on the interpretation of any provision.&nbsp;Throughout these Terms the use of the word “including” means “including but not limited to.” If any part of these Terms is held to be invalid or unenforceable, then the unenforceable part will be given effect to the greatest extent possible, and the remaining parts will remain in full force and effect.&nbsp;</li>
            <li><b>Governing Law</b>. These Terms are governed by the laws of the State of New York without regard to conflict of law principles. You and Whop submit to the personal and exclusive jurisdiction of&nbsp;the state courts and federal courts located within New York, NY for resolution of any lawsuit or court proceeding permitted under these Terms. We operate the Service from our offices in New York, and we make no representation that Materials included in the Service are appropriate or available for use in other locations.&nbsp;</li>
            <li><b>Privacy Policy</b>. Please read the&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>Whop Privacy Policy</u></a>&nbsp;(the “<b>Privacy Policy</b>”) carefully for information relating to our collection, use, storage, and disclosure of your personal information. The Whop&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>Privacy Policy</u></a>&nbsp;is incorporated by this reference into, and made a part of, these Terms.&nbsp;</li>
            <li><b>Additional Terms</b>. Your use of the Service is subject to all additional terms, policies, rules, or guidelines applicable to the Service or certain features of the Service that we may post on or link to from the Service (the “<b>Additional Terms</b>”). The purchase or sale of certain Products may also require Additional Terms. All Additional Terms are incorporated by this reference into, and made a part of, these Terms.&nbsp;</li>
            <li><b>Consent to Electronic Communications</b>. By using the Service, you consent to receiving certain electronic communications from us as further described in our&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>Privacy Policy</u></a>. Please read our&nbsp;<a href="https://whop.com/privacy" class="text-whop-primary underline"><u>Privacy Policy</u></a>&nbsp;to learn more about our electronic communications practices. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that those communications be in writing.<b>&nbsp;</b></li>
            <li><b>Contact Information</b>. The Service is offered by Whop Inc., located at 10 Grand St. – 13A, Brooklyn, NY 11249. You may contact us by sending correspondence to that address or by emailing us at support@whop.com.&nbsp;</li>
            <li><b>Notice to California Residents</b>. If you are a California resident, then under California Civil Code&nbsp;Section 1789.3, you may contact the Complaint Assistance Unit of the Division of Consumer&nbsp;Services of the California Department of Consumer Affairs in writing at 1625 N. Market Blvd., Suite S-202, Sacramento, California 95834, or by telephone at +1-800-952-5210 in order to resolve a complaint regarding the Service or to receive further information regarding use of the Service.&nbsp;</li>
            <li><b>No Support</b>. We are under no obligation to provide support for the Service. In instances where we may offer support, the support will be subject to published policies.&nbsp;</li>
            <li><b>No Obligation to Provide Export or Download of Information or Data</b>. Whop may allow you to access, via functionality provided by the Service, certain information or data relating to your use of the Service, but you acknowledge that such access is provided in Whop’s sole discretion, and Whop has no obligation to make any information or data available to you for export or download.</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b><u>20. Notice Regarding Apple</u></b></p>
         <p class="text-paragraph2 text-whop-black inline-table w-full">This Section 20 only applies to the extent you are using our mobile application on an iOS device. You acknowledge that these Terms are between you and Whop only, not with Apple Inc. (“<b>Apple</b>”), and Apple is not responsible for the Service or the content of it. Apple has no obligation to furnish any maintenance and support services with respect to the Service. If the Service fails to conform to any applicable warranty, you may notify Apple, and Apple will refund any applicable purchase price for the mobile application to you. To the maximum extent permitted by applicable law, Apple has no other warranty obligation with respect to the Service. Apple is not responsible for addressing any claims by you or any third party relating to the Service or your possession and/or use of the Service, including:</p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li>(1) product liability claims;</li>
            <li>(2) any claim that the Service fails to conform to any applicable legal or regulatory requirement; or</li>
            <li>(3) claims arising under consumer protection or similar legislation.</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full">Apple is not responsible for the investigation, defense, settlement, and discharge of any third party claim that the Service and/or your possession and use of the Service infringe a third party’s intellectual property rights. You agree to comply with any applicable third-party terms when using the Service. Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary of these Terms. You hereby represent and warrant that:</p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li>(a) you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a “terrorist supporting” country; and</li>
            <li>(b) you are not listed on any U.S. Government list of prohibited or restricted parties.&nbsp;&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Software Access Addendum</b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Description of Software Access Feature</b>. If you are a Seller, the Service may permit you to make software of yours (“<b>Software</b>”) available to Buyers. If you are a Buyer, the Service may permit you to purchase a license to Software made available by a Seller. This Software Access Addendum will apply to any such use of the Service.&nbsp;&nbsp;</li>
            <li><b>Delivery</b>. Once a Buyer purchases a subscription to a Seller’s Software, Seller agrees to promptly deliver copies such Software to Buyer.&nbsp;</li>
            <li><b>Software License</b>. If you are a Seller, you agree to grant the Buyer a license to the purchased Software under your applicable end user license.&nbsp;&nbsp;</li>
            <li><b>Software Terms</b>. Seller may choose to require the acceptance additional terms governing the use of the Software (“<b>Software Terms</b>”). If any Software Terms are required in connection with access to Software, all Buyers of such Software agree to be bound by such Software Terms.&nbsp;&nbsp;&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Discord Management Addendum</b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Description of Discord Management Feature</b>. If you are a Seller, the Service may permit you to make access to your discord community (“<b>Community</b>”) available to Buyers. If you are a Buyer, the Service may permit you to purchase access to a Community made available by a Seller. This Discord Management Addendum will apply to any such use of the Service.&nbsp;&nbsp;</li>
            <li><b>Discord Management</b>. If you are a Seller, you agree to grant Whop management rights to your Community, including the ability to add or remove Community members as necessary to provide this feature to you.&nbsp;</li>
            <li><b>Discord Account</b>. If you are a Buyer, you agree to link your discord account to your account on the Service and to allow Whop to add you to the Communities you have purchased access to. Your discord account will be deemed a Linked Account under these Terms.&nbsp;</li>
            <li><b>Discord Access</b>. If you are a Seller of Software, you hereby grant Buyers the right to access any Community they have purchased access to.&nbsp;&nbsp;</li>
            <li><b>Community Terms</b>. Seller may make available additional terms governing the Community (“Community Terms”). If any Community Terms are required in connection with access to a Community, you agree to be bound by such Community Terms<b>.&nbsp;</b></li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"><b>Software Rental Addendum</b></p>
         <ol class="text-paragraph2 text-whop-black list-inside list-decimal pl-4">
            <li><b>Description of Software Rental Feature</b>. If you are a Buyer who has purchased access to Software via the Service, the Service may permit you to make such Software available to other users (“<b>Renters</b>”) for a period of time (“<b>Rental Period</b>”). The Service may permit you to rent such Software from a Buyer. This Software Rental Addendum will apply to any such use of the Service. This Software Rental Addendum also hereby incorporates the Software Access Addendum by reference.&nbsp;</li>
            <li><b>Delivery</b>. On the start date of a Rental Period, Whop will facilitate the delivery of the Software to Renter. Buyer agrees to allow Whop to facilitate the delivery of the Software to Renter.&nbsp;</li>
            <li><b>Software License</b>. If you are a Seller making your Software available for rental, you agree to grant the Renter a license to the rented Software under your applicable end user license for the duration of the Rental Period.&nbsp;&nbsp;</li>
            <li><b>Software Terms</b>. If you are a Renter, you agree to be bound by any applicable Software Terms.&nbsp;</li>
         </ol>
         <p class="text-paragraph2 text-whop-black inline-table w-full"></p>
      </div>
   </div>
</div>  )
}

export default Tos